"""empty message

Revision ID: 2992ec11750
Revises: None
Create Date: 2015-12-07 22:57:09.806460

"""

# revision identifiers, used by Alembic.
revision = '2992ec11750'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('email', sa.Unicode(length=64), nullable=True),
    sa.Column('mobile', sa.Unicode(length=64), nullable=True),
    sa.Column('openid', sa.Unicode(length=128), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Interval(), nullable=True),
    sa.Column('total_distance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(length=64), nullable=True),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('need_validation', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.openid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
