"""initial migration

Revision ID: 3e48f2ce10f
Revises: None
Create Date: 2015-04-29 00:32:09.737269

"""

# revision identifiers, used by Alembic.
revision = '3e48f2ce10f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('email', sa.Unicode(length=64), nullable=True),
    sa.Column('mobile', sa.Unicode(length=64), nullable=True),
    sa.Column('openid', sa.Unicode(length=128), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
