"""empty message

Revision ID: 41da8dfa8dd
Revises: 482a7a2e263
Create Date: 2015-12-07 22:34:34.294732

"""

# revision identifiers, used by Alembic.
revision = '41da8dfa8dd'
down_revision = '482a7a2e263'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('speed', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('total_distance', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_distance')
    op.drop_column('tasks', 'speed')
    op.drop_column('tasks', 'distance')
    ### end Alembic commands ###
